//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerInventory_tblLogRecords_TEST
    {
        public int Count { get; set; }
        public string Trigger { get; set; }
        public string Timestamp { get; set; }
        public string ComputerName { get; set; }
        public string UserName { get; set; }
        public string SerialNumber { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Memory { get; set; }
        public string OS { get; set; }
        public string NetworkAdapter { get; set; }
        public string MACAddress { get; set; }
        public string IPAddress { get; set; }
    }
}
