//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerInventory_tblMain
    {
        public string CompName { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Make { get; set; }
        public Nullable<int> Model { get; set; }
        public string SN { get; set; }
        public string User { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public string Location { get; set; }
        public Nullable<int> Dept { get; set; }
        public string Transferred { get; set; }
        public Nullable<System.DateTime> Purchase { get; set; }
        public Nullable<System.DateTime> AuxComputerDate { get; set; }
        public byte[] writeConflict { get; set; }
        public Nullable<int> OwnedBy { get; set; }
        public string Status { get; set; }
    }
}
