//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerInventory_tblParse
    {
        public string Activity { get; set; }
        public string Timestamp { get; set; }
        public string ComputerName { get; set; }
        public string UserName { get; set; }
        public string ServiceTag { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Memory { get; set; }
        public string OS { get; set; }
        public string OSSP { get; set; }
        public string OSVersion { get; set; }
        public string ProcessorDesc { get; set; }
        public string Processor { get; set; }
        public string Level { get; set; }
        public string ClockSpeed { get; set; }
        public string PRocessorID { get; set; }
        public string Network { get; set; }
        public string MAC { get; set; }
        public string IP { get; set; }
    }
}
