//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestTemp1Inventory
    {
        public int DifferenceItemId { get; set; }
        public Nullable<int> TestId { get; set; }
        public string SerialNum { get; set; }
        public string Type { get; set; }
    }
}
